import { ImageResponse } from 'next/og';
import { site } from '@/content/site';
import { logoMarkWillowDataUri as markDataUri } from '@/lib/og-logo';

export const alt = `${site.name} — ${site.tagline}`;
export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';

/**
 * Satori cannot do CSS masks, so the mark is inlined as a pre-painted willow
 * PNG (generated by scripts/extract-logo.mjs) rather than the mask the site
 * itself uses.
 *
 * Brand OG card. Uses a system stack rather than fetching Bricolage at build
 * time — a webfont here costs a network round trip on every regeneration and
 * the card is set large enough that the difference is not worth it.
 */

export default async function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'space-between',
          backgroundColor: '#171613',
          padding: '72px',
          fontFamily: 'system-ui, sans-serif',
        }}
      >
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <img src={markDataUri} width={48} height={48} alt="" />
          <div style={{ color: '#F6F5F1', fontSize: 34, fontWeight: 800, letterSpacing: '-1px' }}>
            {site.name}
          </div>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div
            style={{
              color: '#F6F5F1',
              fontSize: 78,
              fontWeight: 800,
              lineHeight: 1.03,
              letterSpacing: '-3px',
              maxWidth: 950,
              display: 'flex',
              flexWrap: 'wrap',
            }}
          >
            Ads that put real leads in your&nbsp;
            <span
              style={{
                backgroundColor: '#FFBF46',
                color: '#1B1A17',
                padding: '0 14px',
                borderRadius: 12,
              }}
            >
              WhatsApp
            </span>
          </div>
          <div style={{ color: 'rgba(246,245,241,0.65)', fontSize: 28, marginTop: 28 }}>
            Meta ads for local businesses across India
          </div>
        </div>

        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            color: 'rgba(246,245,241,0.5)',
            fontSize: 24,
            borderTop: '1px solid rgba(246,245,241,0.15)',
            paddingTop: 28,
          }}
        >
          <span>basugrow.com</span>
          <span>@{site.contact.instagram}</span>
        </div>
      </div>
    ),
    size,
  );
}
